repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [python]
      - id: autoflake
        name: autoflake
        entry: uv run autoflake
        language: system
        types: [python]
        args: [--remove-all-unused-imports, --remove-unused-variables, --in-place]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args: [
          --fail-under=8.0,
          --disable=missing-function-docstring,
          --disable=missing-class-docstring,
          --disable=too-few-public-methods,
          --disable=redefined-outer-name
        ]
